'use client';
import { useState } from 'react';
import { ArrowUpRight, ArrowDown, MessageCircle } from 'lucide-react';
import { Dialog, DialogTrigger, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Photo, Wordmark, links } from './Opening';

export function BrandStatement(){return <section className="statement section" id="philosophy"><span className="eyebrow">01 / THE ART OF PRESERVATION</span><h2 className="reveal-text">NOT JUST CLEAN.<br/><span className="muted">PRESERVED.</span></h2><div className="statement-bottom"><span className="small-wordmark">LUXÉ SIGNATURE</span><p>For the lines that made you look twice. For the feeling that never gets old. A considered approach to caring for the car you love.</p></div></section>}

const studies=[{name:'PORSCHE 911',service:'A study in protection',image:'hero',number:'01',description:'Sculpted bodywork. Uninterrupted reflections. This illustrative campaign explores how paint protection can be presented with the same care as the machine itself.'},{name:'THE INNER SANCTUM',service:'A study in detail',image:'interior',number:'02',description:'Soft leather, fine stitching and the surfaces closest to the driver. An illustrative campaign exploring the tactile side of automotive care.'}];
export function SelectedWork(){const [selected,setSelected]=useState<number|null>(null);return <section className="work section" id="work"><div className="section-heading"><span className="eyebrow">07 / THE AUTOMOTIVE EDIT</span><span className="eyebrow muted">A CONCEPT CAMPAIGN</span></div><div className="work-heading"><h2 className="display reveal-text">SELECTED<br/><span className="muted">MACHINES.</span></h2><p>Objects of obsession.<br/>A visual direction for the LUXÉ world.</p></div><div className="work-layout">{studies.map((s,i)=><button className={`work-item work-${i} reveal-image`} onClick={()=>setSelected(i)} key={s.number} aria-label={`View ${s.name} concept study`}><div className="work-image"><Photo name={s.image} alt={`${s.name} — illustrative campaign image`}/><span className="view-project">VIEW <ArrowUpRight size={15}/></span><span className="work-number">/ {s.number}</span></div><div className="work-caption"><h3>{s.name}</h3><ArrowUpRight size={20}/></div><p>{s.service} <span>CONCEPT STUDY</span></p></button>)}</div><p className="disclosure">AI-generated campaign imagery. These studies are not verified LUXÉ customer vehicles or completed projects.</p><Dialog open={selected!==null} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="project-dialog">{selected!==null&&<><Photo name={studies[selected].image} alt={`${studies[selected].name} concept campaign`}/><span className="eyebrow gold">R. ATELIER / CONCEPT STUDY {studies[selected].number}</span><DialogTitle>{studies[selected].name}</DialogTitle><DialogDescription>{studies[selected].description} It does not represent a completed LUXÉ project.</DialogDescription><a href="#contact" className="text-link" onClick={()=>setSelected(null)}>EXPLORE THE POSSIBILITIES <ArrowUpRight size={18}/></a></>}</DialogContent></Dialog></section>}

export function Philosophy(){return <section className="philosophy section"><span className="eyebrow">THE LUXÉ POINT OF VIEW</span><h2 className="reveal-text">ANYONE CAN<br/>CLEAN A CAR.<br/><span>PRESERVING ONE<br/>IS DIFFERENT.</span></h2><div className="philosophy-bottom"><span className="gold-dash"/><p>Respect the material. Understand the finish.<br/>Pay attention to what others pass by.<br/>That is the art of preservation.</p></div></section>}

export function Studio(){return <section className="studio section" id="about"><div className="studio-photo reveal-image"><Photo name="interior" alt="Illustrative sports car interior, representing the concept’s material direction"/><span className="image-caption">CAMPAIGN DETAIL / ILLUSTRATIVE IMAGE</span></div><div className="studio-copy"><span className="eyebrow">09 / LUXÉ SIGNATURE DETAILING</span><h2 className="display reveal-text">A PLACE FOR<br/>THE PARTICULAR.</h2><p>Based in Taman Sentosa, Klang, LUXÉ Signature Detailing offers interior and exterior care, coatings, paint protection and restoration for car enthusiasts and owners.</p><p>Bring your vehicle. Share what matters to you.<br/>Explore the care it deserves.</p><div className="studio-location"><span className="eyebrow gold">VISIT LUXÉ</span><address>61, Jalan Laksamana 6<br/>Taman Sentosa, 41200 Klang<br/>Selangor, Malaysia</address><a href="https://www.google.com/maps/search/?api=1&query=61%20Jalan%20Laksamana%206%20Taman%20Sentosa%2041200%20Klang" target="_blank" rel="noopener noreferrer" className="text-link">GET DIRECTIONS <ArrowUpRight size={18}/></a></div></div></section>}

export function FinalCTA(){return <section className="final-cta" id="contact"><Photo name="hero" alt="Illustrative graphite sports car in a dark studio"/><div className="final-shade"/><div className="final-content"><span className="eyebrow">10 / YOUR NEXT CHAPTER</span><h2 className="display reveal-text">YOUR CAR<br/>DESERVES<br/>MORE.</h2><p>Experience LUXÉ Signature Detailing.</p><div className="final-actions"><Dialog><DialogTrigger className="button solid">BOOK YOUR DETAIL <ArrowUpRight size={19}/></DialogTrigger><DialogContent className="booking-dialog"><span className="eyebrow gold">YOUR NEXT DETAIL</span><DialogTitle>START A CONVERSATION.</DialogTitle><DialogDescription>This is an independent concept by R. Atelier. Bookings are handled directly by LUXÉ Signature. Continue to their published contact details to discuss your vehicle, service and availability.</DialogDescription><a className="button solid" href="https://wa.me/60178873474" target="_blank" rel="noopener noreferrer">CONTINUE TO WHATSAPP <ArrowUpRight size={18}/></a><a href="tel:+60178873474" className="text-link">CALL +60 17-887 3474 <ArrowUpRight size={17}/></a><p className="disclosure">No booking is submitted through this concept website.</p></DialogContent></Dialog><a className="text-link" href="https://wa.me/60178873474" target="_blank" rel="noopener noreferrer"><MessageCircle size={18}/> WHATSAPP LUXÉ <ArrowUpRight size={17}/></a></div><span className="contact-note">CONTACT LINKS OPEN LUXÉ’S REAL BUSINESS CHANNELS.</span></div><span className="final-caption">THE ART OF PRESERVATION.</span></section>}

export function Footer(){return <footer className="footer"><div className="footer-top"><div><Wordmark/><p>Precision. Protection. Preservation.</p></div><div><span className="eyebrow">EXPLORE</span>{links.map(([name,url])=><a href={url} key={name}>{name}</a>)}</div><div><span className="eyebrow">GET IN TOUCH</span><a href="tel:+60178873474">+60 17-887 3474</a><a href="mailto:luxe.signature.detailing@gmail.com">Email LUXÉ <ArrowUpRight size={12}/></a><a href="https://wa.me/60178873474" target="_blank" rel="noopener noreferrer">WhatsApp <ArrowUpRight size={12}/></a><a href="https://www.luxesignature.com.my/" target="_blank" rel="noopener noreferrer">Official website <ArrowUpRight size={12}/></a></div><div><span className="eyebrow">FIND LUXÉ</span><address>61, Jalan Laksamana 6<br/>Taman Sentosa, 41200 Klang<br/>Selangor, Malaysia</address><p>Daily / 10:00 – 20:00<br/><span className="footer-note">Confirm opening hours before visiting.</span></p></div></div><div className="footer-wordmark" aria-hidden="true">LUXÉ</div><div className="footer-bottom"><span>CONCEPT REDESIGN BY <strong>R. ATELIER</strong></span><p>An unsolicited, independent concept. Not the official LUXÉ Signature website.</p><a href="#" aria-label="Back to top">BACK TO TOP <ArrowDown size={13} style={{transform:'rotate(180deg)'}}/></a></div></footer>}
