'use client';
import { useEffect, useState } from 'react';
import { ArrowUpRight, ArrowDown, Menu } from 'lucide-react';
import { Dialog, DialogTrigger, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
export const links = [['Services','#services'],['Protection','#protection'],['Detailing','#detailing'],['Our Work','#work'],['About','#about']];
export function Wordmark() { return <span className="wordmark">AUTO<small>DETAILING CONCEPT</small></span> }
export function Navigation(){ const [scrolled,setScrolled]=useState(false); const [open,setOpen]=useState(false); useEffect(()=>{ const fn=()=>setScrolled(window.scrollY>40);fn();window.addEventListener('scroll',fn,{passive:true});return()=>window.removeEventListener('scroll',fn)},[]);
return <><a className="skip-link" href="#main">Skip to content</a><header className={`navigation ${scrolled?'scrolled':''}`}><a href="#" aria-label="Auto Detailing home"><Wordmark/></a><nav className="desktop-nav" aria-label="Main navigation">{links.map(([title,url])=><a key={title} href={url}>{title}</a>)}</nav><a className="nav-book" href="#contact">GET IN TOUCH <ArrowUpRight size={16}/></a><Dialog open={open} onOpenChange={setOpen}><DialogTrigger className="mobile-menu" aria-label="Open navigation"><Menu/></DialogTrigger><DialogContent className="menu-dialog"><DialogTitle><Wordmark/></DialogTitle><DialogDescription className="sr-only">Explore Auto Detailing</DialogDescription><nav aria-label="Mobile navigation">{links.map(([title,url])=><a key={title} href={url} onClick={()=>setOpen(false)}>{title}<ArrowUpRight/></a>)}<a href="#contact" onClick={()=>setOpen(false)}>Get in touch<ArrowUpRight/></a></nav><p className="eyebrow">AN INDEPENDENT CONCEPT BY RUZAIMAN</p></DialogContent></Dialog></header></> }
export function Photo({name,alt,className='',eager=false}:{name:string;alt:string;className?:string;eager?:boolean}){return <img className={className} src={`/images/${name}-1536.webp`} srcSet={`/images/${name}-768.webp 768w, /images/${name}-1536.webp 1536w`} sizes="(max-width: 768px) 100vw, 100vw" width="1536" height="1024" alt={alt} loading={eager?'eager':'lazy'} fetchPriority={eager?'high':'auto'} decoding="async"/>}
export function Hero(){return <section className="hero" aria-labelledby="hero-title"><Photo name="hero" alt="Concept photograph of a graphite Porsche 911 beneath silver studio lights" className="hero-image" eager/><div className="hero-shade"/><div className="hero-content"><div className="eyebrow hero-eyebrow"><span className="gold-dash"/>AUTOMOTIVE CARE. ELEVATED.</div><h1 id="hero-title"><span>PRESERVE</span><span>PERFECTION.</span></h1><p>Precision detailing and automotive protection.<br/>For machines worth preserving.</p><div className="hero-actions"><a className="button solid" href="#services">EXPLORE SERVICES <ArrowUpRight size={18}/></a><a className="text-link" href="#contact">GET IN TOUCH <ArrowUpRight size={16}/></a></div></div><div className="hero-bottom"><a href="#philosophy"><span className="scroll-circle"><ArrowDown size={17}/></span> SCROLL TO DISCOVER</a><span>AUTOMOTIVE DETAILING <span className="gold-dot">●</span></span></div><div className="concept-stamp">RUZAIMAN / INDEPENDENT CONCEPT</div></section>}
